// Mocks generated by Mockito 5.0.7 from annotations
// in fast_shopping/test/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fast_shopping_bloc/src/data/shopping_list_repository.dart'
    as _i2;
import 'package:fast_shopping_bloc/src/models/shopping_list.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [ShoppingListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListRepository extends _i1.Mock
    implements _i2.ShoppingListRepository {
  MockShoppingListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getSelectedListId() =>
      (super.noSuchMethod(Invocation.method(#getSelectedListId, []),
          returnValue: Future<String?>.value('')) as _i3.Future<String?>);
  @override
  _i3.Future<void> saveSelectedListId(String? id) =>
      (super.noSuchMethod(Invocation.method(#saveSelectedListId, [id]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.Future<List<_i4.ShoppingList>> getLists() =>
      (super.noSuchMethod(Invocation.method(#getLists, []),
              returnValue:
                  Future<List<_i4.ShoppingList>>.value(<_i4.ShoppingList>[]))
          as _i3.Future<List<_i4.ShoppingList>>);
  @override
  _i3.Future<void> saveLists(List<_i4.ShoppingList>? lists) =>
      (super.noSuchMethod(Invocation.method(#saveLists, [lists]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
}
