include: package:lint/analysis_options.yaml

linter:
    rules:
        - sort_constructors_first
        - prefer_single_quotes

analyzer:
    exclude:
        - lib/l10n/messages_*.dart
        - lib/l10n/l10n.dart
        - lib/**/*.freezed.dart
