name: fast_shopping
description: Simple app for easy shopping list making, developed with simplicity in mind.

publish_to: 'none'

version: 3.0.0+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^1.0.0+5
  clock: ^1.0.1
  crashlytics:
    path: crashlytics/foss # CD changes me 🤖
  fast_shopping_bloc:
    path: fast_shopping_bloc
  flutter_hooks: ^0.15.0
  flutter_bloc: ^7.0.0-dev.2
  flutter_svg: ^0.19.0
  implicitly_animated_reorderable_list: ^0.4.0-dev+3
  intl: ^0.16.1
  md2_tab_indicator: ^1.0.2
  shared_preferences: ^0.5.6+1
  timeago: ^2.0.22
  url_launcher: ^5.4.2
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  image: ^2.1.19
  lint: ^1.2.0
  mockito: ^4.1.3
  test: ^1.15.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/arrow_fab.svg
    - assets/arrow_bottom_app_bar.svg
    - assets/gone_shopping.svg
    - assets/shopping_bags_woman.svg
