name: fast_shopping
description: Very simple and straightforward shopping list application.
version: 1.1.0+3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.4.3
  scoped_model: ^1.0.1

dev_dependencies:
  intl_translation: ^0.17.2

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
