name: fast_shopping
description: Very simple and straightforward shopping list application.

version: 2.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  devicelocale: ^0.2.1
  timeago: ^2.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    # Internationalization
    - lib/i18n/en_US.json
    - lib/i18n/pl_PL.json
