name: fast_shopping
description: Simple app for easy shopping list making, developed with simplicity in mind.


publish_to: 'none'

version: 3.0.0+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^1.0.0+5
  flutter_hooks: ^0.15.0
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  intl: ^0.16.1
  list_diff: ^1.3.2
  md2_tab_indicator: ^1.0.2
  shared_preferences: ^0.5.6+1
  timeago: ^2.0.22
  url_launcher: ^5.4.2
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  arbify: ^0.0.11
  build_runner: ^1.7.3
  freezed: ^0.12.3
  image: ^2.1.19
  lint: ^1.2.0
  test: ^1.15.5

dependency_overrides:
  analyzer: ^0.41.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/arrow_fab.svg
    - assets/arrow_bottom_app_bar.svg
    - assets/shopping_bags_woman.svg

arbify:
  url: https://arb.wolszon.me
  project_id: 3
