platform :ios do
    lane :release do
        setup_ci

        app_store_connect_api_key(
            key_id: ENV["APPLE_APP_STORE_CONNECT_API_KEY_ID"],
            issuer_id: ENV["APPLE_APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
            key_content: ENV["APPLE_APP_STORE_CONNECT_API_KEY"]
        )

        match(
            type: "appstore",
            app_identifier: ENV["APPLE_APP_IDENTIFIER"],
            git_url: ENV["MATCH_GIT_URL"]
        )

        update_project_provisioning(
            xcodeproj: "ios/Runner.xcodeproj",
            profile: ENV["sigh_#{ENV["APPLE_APP_IDENTIFIER"]}_appstore_profile-path"],
            build_configuration: "Release",
            code_signing_identity: "Apple Distribution"
        )

        export_options = <<-EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>#{ENV["APPLE_APP_IDENTIFIER"]}</key>
		<string>#{ENV["sigh_#{ENV["APPLE_APP_IDENTIFIER"]}_appstore_profile-name"]}</string>
	</dict>
</dict>
</plist>
        EOF
        File.write("build/ExportOptions.plist", export_options)

        sh('flutter build ipa --release --export-options-plist=build/ExportOptions.plist')

        upload_to_app_store(
            ipa: "build/ios/iphoneos/Runner.app",

            force: true,
            overwrite_screenshots: true,
            submit_for_review: true,
            automatic_release: true,
            submission_information: {
                add_id_info_serves_ads: false,
                add_id_info_tracks_action: false,
                add_id_info_tracks_install: false,
                add_id_info_uses_idfa: false,

                content_rights_contains_third_party_content: false,
                content_rights_has_rights: false,

                export_compliance_platform: 'ios',
                export_compliance_compliance_required: false,
                export_compliance_encryption_updated: false,
                export_compliance_app_type: nil,
                export_compliance_uses_encryption: false,
                export_compliance_is_exempt: false,
                export_compliance_contains_third_party_cryptography: false,
                export_compliance_contains_proprietary_cryptography: false,
                export_compliance_available_on_french_store: false
            },
            precheck_include_in_app_purchases: false # Doesn't work with App Store Connect API key
        )
    end
end
