name: fast_shopping_bloc

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.0.0
  clock: ^1.1.0
  collection: ^1.15.0
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  uuid: ^3.0.4

dev_dependencies:
  coverage: ^1.0.2
  bloc_test: ^8.0.0
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  lint: ^1.5.3
  mockito: ^5.0.7
  test: ^1.17.3
