name: fast_shopping_bloc

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.0
  clock: ^1.0.1
  freezed_annotation: ^0.12.0

dev_dependencies:
  bloc_test: ^7.1.0
  build_runner: ^1.7.3
  freezed: ^0.12.3
  lint: ^1.2.0
  mockito: ^4.1.3
  test: ^1.15.7
